version: "3"

services:
    vre:
        build:
            context: .
            dockerfile: api.Dockerfile
        ports:
            - "5000"
        environment:
            - PORT=5000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        restart: always
    nginx:
        image: nginx:1.21.4-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        depends_on:
            - vre
        restart: always
