version: "3"

services:
    vre:
        build: Dockerfile.api
        ports:
            - "5000"
        environment:
            - PORT=5000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        restart: always
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certificates/conf:/etc/letsencrypt
            - ./certificates/www:/var/www/certbot
        entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    nginx:
        image: nginx:1.21.4-alpine
        volumes:
            - ./certificates/conf:/etc/letsencrypt
            - ./certificates/www:/var/www/certbot
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        ports:
            - "80:80"
            - "443:443"
        restart: always
