version: "3"

services:
    vre:
        build: Dockerfile.api
        ports:
            - "5000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        restart: always
