# name: Deploy VRE

# on:
#     push:
#         branches:
#             - deployment
#     workflow_dispatch:

# jobs:
#     deploy:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Deploy VRE
#               uses: appleboy/ssh-action@v0.1.2
#               with:
#                   username: ${{secrets.SSH_USERNAME}}
#                   host: ${{secrets.SSH_HOST}}
#                   key: ${{secrets.SSH_KEY}}
#                   script: |
#                       cd Chainlink-VRE-Adapter/src
#                       docker-compose down
#                       git pull
#                       bash start.sh
